### ISSUE TITLE
improve pytest exercise

### ISSUE THREAD

**Issue by DaniBodor** [esciencecenter-digital-skills/good-practices-lesson#7]
The current exercise (see beloow) revolves around solving the erratic behavior of using a mutable argument in a function. This turned out to be such a python specific and detailed issue, that many people got stuck on why this even happens rather than getting to the point of the exercise (getting acquainted with Pytest).
We should think of a new exercise for this (or drop the exercise altogether, but then it becomes a bit dry).

Current exercise:

> In the code below (as in slides)
> 
> 1. Add a test to catch "problematic" behavior of the function.
>     - don't fix the function (yet)
> 2. Run pytest to see what the response looks like. 
>     - what information can you gather from the response?
> 3. Fix the function and rerun the test
> 
> 
> ```python
> def fahrenheit_to_celsius(temp_list, converted_temps=[]):
>     for temp in temp_list:
>         temp_c = (temp - 32.0) * (5.0/9.0)
>         converted_temps.append(temp_c)
>     return converted_temps
> 
> def test_convert():
>     assert fahrenheit_to_celsius([32.0, 77.0]) == [0.0, 25.0]
>     assert (fahrenheit_to_celsius([100], converted_temps = [0.0, 25.0])
>             == [0.0, 25.0, 37.77777777777778])
> ```

**Comment by lyashevska** [comment]
This example was removed as it was too convoluted and difficult to follow.
